// index.js
const express = require('express');
const app = express();
const authRoutes = require('./routes/auth');
const profileRoutes = require('./routes/profile');
const referralRoutes = require('./routes/referral');
const userRoutes = require('./routes/user');
const productRoutes = require('./routes/product');
const albumRoutes = require('./routes/album');
const paymentRoutes = require('./routes/payment');
const albumAccessRoutes = require('./routes/albumAccess');
const stripeWebhookRoutes = require('./routes/stripeWebhook');
const chatRoutes = require('./routes/chatRoutes');
const errorHandler = require('./middleware/errorHandler');
app.use(express.json());
console.log('authRoutes:', authRoutes);
console.log('profileRoutes:', profileRoutes);
console.log('referralRoutes:', referralRoutes);
console.log('userRoutes:', userRoutes);
console.log('productRoutes:', productRoutes);
console.log('albumRoutes:', albumRoutes);
console.log('paymentRoutes:', paymentRoutes);
console.log('albumAccessRoutes:', albumAccessRoutes);
console.log('stripeWebhookRoutes:', stripeWebhookRoutes);
console.log('chatRoutes:', chatRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api/referral', referralRoutes);
app.use('/api/user', userRoutes);
app.use('/api/products', productRoutes);
app.use('/api/albums', albumRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/album-access', albumAccessRoutes);
app.use('/webhook', stripeWebhookRoutes);
app.use('/api/chat', chatRoutes);
app.use(errorHandler);
app.get('/', (req, res) => {
    res.send('Invest App Backend is running!');
});
//
module.exports = app;
